import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('browse, search, title, episode, and real provider resolution stay connected', async ({ page }, testInfo) => {
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));
  await page.goto('/catalogue');
  await expect(page.getByRole('heading', { name: 'All anime' })).toBeVisible();
  await page.getByRole('searchbox', { name: 'Search catalogue' }).fill('Candy Caries');
  await page.getByRole('button', { name: /Search/ }).click();
  await expect(page).toHaveURL(/q=Candy(?:\+|%20)Caries/i);
  await page.waitForTimeout(250);
  expect(pageErrors, `Uncaught browser errors: ${pageErrors.join(' | ')}`).toEqual([]);
  await expect(page.getByRole('heading', { name: 'Candy Caries' })).toBeVisible();
  await page.getByRole('button', { name: 'Watchlist' }).click();
  await page.getByRole('link', { name: 'Candy Caries', exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'Candy Caries' })).toBeVisible();
  await expect(page.getByText('22 of 22 episodes')).toBeVisible();
  await page.getByRole('link', { name: /Start watching/ }).click();
  await expect(page.getByRole('heading', { name: 'Servers' })).toBeVisible();
  await expect(page.getByRole('button', { name: /HD-1/ })).toBeVisible();
  await expect(page).toHaveURL(/server=\d+/, { timeout: 15_000 });
  const firstServerId = new URL(page.url()).searchParams.get('server');
  const frame = page.locator('iframe[title="Episode player"]');
  await expect(frame).toHaveCount(0);
  await page.getByRole('button', { name: 'Play here' }).click();
  await expect(frame).toHaveAttribute('src', /^https:\/\/megaplay\.buzz\/stream\/s-2\//);
  await expect(frame).not.toHaveAttribute('sandbox', /.+/);
  await expect(frame).toHaveAttribute('referrerpolicy', 'strict-origin-when-cross-origin');
  await expect(page.getByRole('link', { name: /Open provider/ })).toHaveAttribute('rel', /noreferrer/);
  const alternateServer = page.getByRole('button', { name: /HD-2/ });
  await alternateServer.click();
  await expect(alternateServer).toHaveAttribute('aria-pressed', 'true');
  const alternateServerId = new URL(page.url()).searchParams.get('server');
  expect(alternateServerId).not.toBe(firstServerId);
  await page.goBack();
  await expect.poll(() => new URL(page.url()).searchParams.get('server')).toBe(firstServerId);
  await expect(page.getByRole('button', { name: /HD-1/ })).toHaveAttribute('aria-pressed', 'true');
  await page.goForward();
  await expect.poll(() => new URL(page.url()).searchParams.get('server')).toBe(alternateServerId);
  await expect(alternateServer).toHaveAttribute('aria-pressed', 'true');
  const firstEpisodePath = new URL(page.url()).pathname;
  await page.reload();
  await page.getByRole('button', { name: 'Play here' }).click();
  await expect(frame).toHaveAttribute('src', /^https:\/\/megaplay\.buzz\/stream\/s-2\//);
  await page.getByRole('button', { name: /Next/ }).click();
  await expect.poll(() => new URL(page.url()).pathname).not.toBe(firstEpisodePath);
  await page.getByRole('button', { name: /Previous/ }).click();
  await expect.poll(() => new URL(page.url()).pathname).toBe(firstEpisodePath);
  await expect(page.locator('main')).toBeFocused();
  await page.getByRole('button', { name: 'Play here' }).click();
  await expect(frame).toHaveAttribute('src', /^https:\/\/megaplay\.buzz\/stream\/s-2\//);
  await page.getByRole('button', { name: 'Mark watched' }).click();
  await expect(page.getByRole('button', { name: '✓ Watched' })).toHaveAttribute('aria-pressed', 'true');
  await page.getByLabel('Name').fill('QA viewer');
  await page.getByRole('textbox', { name: 'Comment' }).fill('The episode-scoped comment stays on this device.');
  await page.getByRole('button', { name: 'Post comment' }).click();
  await expect(page.getByText('The episode-scoped comment stays on this device.')).toBeVisible();
  await page.screenshot({ path: `evidence/screenshots/${testInfo.project.name}-watch.png`, fullPage: true });
  await page.getByRole('link', { name: 'Home', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Continue watching' })).toBeVisible();
  await expect(page.locator('.continue-card').filter({ hasText: 'Candy Caries' })).toBeVisible();
  await page.screenshot({ path: `evidence/screenshots/${testInfo.project.name}-home.png`, fullPage: true });
  await page.getByRole('link', { name: /My list/ }).click();
  await expect(page.getByRole('heading', { name: 'Saved for later' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Candy Caries' })).toBeVisible();
  await expect(page.getByRole('link', { name: /Candy Caries/ }).last()).toContainText(/Episode/);
});

test('responsive layout, local preferences, and top-level accessibility remain usable', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const response = await page.goto('/catalogue');
  expect(response?.headers()['x-content-type-options']).toBe('nosniff');
  expect(response?.headers()['content-security-policy']).toContain("frame-ancestors 'none'");
  await page.keyboard.press('Tab');
  const skipLink = page.getByRole('link', { name: 'Skip to content' });
  await expect(skipLink).toBeFocused();
  expect(await skipLink.evaluate((element) => getComputedStyle(element).outlineStyle)).not.toBe('none');
  await expect(page.locator('.title-card').first()).toBeVisible();
  const animationDuration = await page.locator('.title-card').first().evaluate((element) => getComputedStyle(element).animationDuration);
  const animationMilliseconds = animationDuration.endsWith('ms') ? Number.parseFloat(animationDuration) : Number.parseFloat(animationDuration) * 1_000;
  expect(animationMilliseconds).toBeLessThanOrEqual(0.01);
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
  expect(overflow).toBeLessThanOrEqual(1);
  await page.getByRole('button', { name: 'Use light theme' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await expect(page.locator('.title-card')).toHaveCount(24);
  await expect(page.locator('.title-card').last()).toBeVisible();
  const results = await new AxeBuilder({ page }).exclude('iframe').analyze();
  expect(results.violations).toEqual([]);
  await page.screenshot({ path: `evidence/screenshots/${testInfo.project.name}-catalogue-light.png`, fullPage: true });
});

test('related title cards resolve to imported local records', async ({ page }) => {
  await page.goto('/title/bungaku-shoujo-kyou-no-oyatsu-hatsukoi-a9cps');
  await expect(page.getByRole('heading', { name: 'Keep the thread' })).toBeVisible();
  const related = page.getByRole('link', { name: 'Arms Alchemy', exact: true }).first();
  await expect(related).toHaveAttribute('href', '/title/arms-alchemy-sjgw9');
  await related.click();
  await expect(page.getByRole('heading', { name: 'Arms Alchemy', exact: true })).toBeVisible();
});
