/** Structural subset of D1's binding API; the Worker Env is generated by Wrangler. */
export interface AccountStatement {
  bind(...values: unknown[]): AccountStatement;
  first<T = Record<string, unknown>>(column?: string): Promise<T | null>;
  all<T = Record<string, unknown>>(): Promise<{ results: T[]; success: boolean }>;
  run(): Promise<{ success: boolean; meta: { changes: number } }>;
}
export interface AccountDatabase {
  prepare(sql: string): AccountStatement;
  batch(statements: AccountStatement[]): Promise<Array<{ success: boolean; meta: { changes: number } }>>;
}

export type CloudAccount = {
  id: string;
  firebase_uid: string;
  email: string;
  recovery_hash: string | null;
  email_verified: number;
  created_at: number;
  auth_revision: number;
  auth_state: 'active' | 'recovering' | 'password-changing' | 'deleting';
  operation_id: string | null;
  operation_error: string | null;
};
export type CloudProfile = { id: string; name: string; avatar: string };
export type CloudSession = {
  token_hash: string;
  account_id: string;
  csrf: string;
  created_at: number;
  last_seen: number;
  expires_at: number;
  device: string;
  auth_revision: number;
  credential_cipher: string;
  checked_at: number;
};
export type IdentityCredentials = {
  uid: string;
  idToken: string;
  refreshToken: string;
  expiresAt: number;
  authenticatedAt: number;
};
export type IdentityUser = {
  uid: string;
  email: string;
  emailVerified: boolean;
  createdAt: number;
  validSince: number;
  passwordUpdatedAt: number;
  disabled: boolean;
};
/** Implemented by the fixed-origin Firebase REST client; injected only by deterministic tests. */
export interface ManagedIdentity {
  readonly recoveryAvailable: boolean;
  signUp(email: string, password: string): Promise<IdentityCredentials>;
  signIn(email: string, password: string): Promise<IdentityCredentials>;
  refresh(credentials: IdentityCredentials): Promise<IdentityCredentials>;
  lookup(credentials: IdentityCredentials): Promise<IdentityUser>;
  changePassword(credentials: IdentityCredentials, password: string): Promise<IdentityCredentials>;
  resetPassword(uid: string, password: string): Promise<void>;
  deleteUser(credentials: IdentityCredentials): Promise<void>;
}
