/** Disposable test inputs, never credentials for an upstream service or a deployed account. */
export const generatedTestPassphrase = (label: string) => `Test-only ${label} ${crypto.randomUUID()}`;
export const generatedTestToken = (label: string) => `test-only-${label}-${crypto.randomUUID()}`;
export const generatedTestApiKey = () => `test_${crypto.randomUUID().replaceAll('-', '')}`;

/** Wrap only RSA bytes generated by the calling test; this helper contains no key material. */
export const testPkcs8Pem = (body: string) => {
  const label = 'PRIVATE KEY';
  return [`-----BEGIN ${label}-----`, body, `-----END ${label}-----`, ''].join('\n');
};
